version: '3.9'

services:
  db:
    container_name: taskninja
    image: postgres:latest
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      SSLMODE: "disable"
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
  app:
    container_name:   app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${GO_PORT}:${GO_PORT}
    volumes:
      - ./cmd/api:/cmd/api
    depends_on:
      - db
    networks:
      - backend



networks:
  backend: